# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Ftxkb2P6PovMbARh4R8egX0W9ny9q76
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
url = "/content/Crop Production data.csv"
df = pd.read_csv(url)

# Data cleaning and preprocessing
df['Crop_Year'] = pd.to_numeric(df['Crop_Year'], errors='coerce')
df['Area'] = pd.to_numeric(df['Area'], errors='coerce')
df['Production'] = pd.to_numeric(df['Production'], errors='coerce')

df.dropna(inplace=True)

# Data visualization using Matplotlib and Seaborn
plt.figure(figsize=(14, 7))

# Visualizing crop production over the years
plt.subplot(2, 1, 1)
sns.lineplot(data=df, x='Crop_Year', y='Production', hue='Crop', ci=None)
plt.title('Crop Production Over the Years')
plt.xlabel('Crop Year')
plt.ylabel('Production')

# Visualizing crop production by season
plt.subplot(2, 1, 2)
sns.barplot(data=df, x='Season', y='Production', hue='Crop', ci=None)
plt.title('Crop Production by Season')
plt.xlabel('Season')
plt.ylabel('Production')

plt.tight_layout()
plt.show()

